-- update isBlock
ALTER TABLE USERS ADD isBlock Bit
ALTER TABLE DonHang ADD total float


CREATE DATABASE ITSS
GO

 USE ITSS
 GO
-- product
CREATE TABLE Loai(
	IDLoai INT IDENTITY(1,1) PRIMARY KEY,
	TenLoai VARCHAR(30)
)

 CREATE TABLE Media(
	IDMedia INT IDENTITY(1,1) PRIMARY KEY,
	Ten VARCHAR(50),
	IDLoai INT,
	GiaTri INT,
	GiaCa INT ,
	FOREIGN KEY (IDLoai) REFERENCES Loai(IDLoai)
)

CREATE TABLE TheLoai(
	IDTheLoai INT IDENTITY(1,1) PRIMARY KEY,
	Ten VARCHAR(50),
	IDLoai INT,
	FOREIGN KEY (IDLoai) REFERENCES Loai(IDLoai)
)

CREATE TABLE NgonNgu(
	IDNN INT IDENTITY(1,1) PRIMARY KEY,
	Ten VARCHAR(30)
)

CREATE TABLE TacGia(
	IDTacGia INT IDENTITY(1,1) PRIMARY KEY,
	Ten VARCHAR(100)
)

CREATE TABLE SangTac(
	IDTacGia INT,
	IDMedia INT,
	PRIMARY KEY (IDTacGia, IDMedia),
	FOREIGN KEY (IDTacGia) REFERENCES TacGia(IDTacGia),
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia)
)

CREATE TABLE Bia(
	IDBia INT IDENTITY(1,1) PRIMARY KEY,
	LoaiBia VARCHAR(30)
)
CREATE TABLE Book(
	IDMedia INT PRIMARY KEY,
	IDBia INT,
	NhaXB VARCHAR(100),
	NgayXB DATE,
	SoTrang INT,
	IDNN INT,
	IDTheLoai INT,
	FOREIGN KEY (IDBia) REFERENCES Bia(IDBia),
	FOREIGN KEY (IDNN) REFERENCES NgonNgu(IDNN),
	FOREIGN KEY (IDTheLoai) REFERENCES TheLoai(IDTheLoai)
)

CREATE TABLE DVD(
	IDMedia INT PRIMARY KEY,
	IDTheLoai INT,
	ThoiLuong FLOAT(2),
	Studio VARCHAR(50),
	IDNN INT,
	PhuDe VARCHAR(50),
	FOREIGN KEY (IDTheLoai) REFERENCES TheLoai(IDTheLoai),
	FOREIGN KEY (IDNN) REFERENCES NgonNgu(IDNN),
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia)
)

CREATE TABLE LoaiDia(
	IDDia INT IDENTITY(1,1) PRIMARY KEY,
	LoaiDia VARCHAR(30)
)

CREATE TABLE BaiHat(
	IDBaiHat INT IDENTITY(1,1) PRIMARY KEY,
	Ten VARCHAR(50),
	IDTacGia INT,
	FOREIGN KEY (IDTacGia) REFERENCES TacGia(IDTacGia)
)

CREATE TABLE DanhSachBaiHat(
	IDMedia INT,
	IDBaiHat INT,
	PRIMARY KEY (IDMedia, IDBaiHat),
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia),
	FOREIGN KEY (IDBaiHat) REFERENCES BaiHat(IDBaiHat)
)

CREATE TABLE CD (
	IDMedia INT PRIMARY KEY,
	HangGhiAm VARCHAR(200),
	IDTheLoai INT,
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia),
	FOREIGN KEY (IDTheLoai) REFERENCES TheLoai(IDTheLoai)
)

CREATE TABLE LD(
	IDMedia INT PRIMARY KEY,
	HangGhiAm VARCHAR(200),
	IDTheLoai INT,
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia),
	FOREIGN KEY (IDTheLoai) REFERENCES TheLoai(IDTheLoai)
)

CREATE TABLE Physical(
	IDMedia INT PRIMARY KEY,
	Barcode INT,
	SoLuong INT,
	MoTa VARCHAR(225),
	NgayNhapKho DATE,
	Size VARCHAR(10),
	KhoiLuong FLOAT(2),
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia)
)

-- users

CREATE TABLE Users(
	IDUser INT IDENTITY PRIMARY KEY,
	Email VARCHAR(30),
	Pass VARCHAR(30),
	isAdmin BIT
)

-- them truong cardnumber for users
ALTER TABLE Users ADD CardNumber VARCHAR(50)

CREATE TABLE Actions(
	IDAction INT IDENTITY PRIMARY KEY,
	Ten VARCHAR(50)
)

CREATE TABLE History(
	IDHistory INT IDENTITY PRIMARY KEY,
	IDMedia INT,
	IDUser INT,
	IDAction INT,
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia),
	FOREIGN KEY (IDUser) REFERENCES Users(IDUser),
	FOREIGN KEY (IDAction) REFERENCES Actions(IDAction)
)

CREATE TABLE Cart(
	IDMedia INT,
	IDUser INT,
	SoLuong INT,
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia),
	FOREIGN KEY (IDUser) REFERENCES Users(IDUser)
)

CREATE TABLE DiaChi(
	IDAddress INT IDENTITY PRIMARY KEY,
	IDUser INT,
	Phone VARCHAR(11),
	Name VARCHAR(50),
	Diachi VARCHAR(225),
	FOREIGN KEY (IDUser) REFERENCES Users(IDUser)
)

-- Thay đổi kiểu của Name, Diachi
ALTER TABLE DiaChi
ALTER COLUMN Name NVARCHAR(50) NOT NULL;
ALTER TABLE DiaChi
ALTER COLUMN Diachi NVARCHAR(225) NOT NULL;


CREATE TABLE DonHang(
	IDDonHang INT IDENTITY PRIMARY KEY,
	IDUser INT,
	IDAddress INT,
	TrangThai VARCHAR(30),
	GhiChu VARCHAR(225),
	FOREIGN KEY (IDUser) REFERENCES Users(IDUser),
	FOREIGN KEY (IDAddress) REFERENCES DiaChi(IDAddress)
)

ALTER TABLE DonHang
ALTER COLUMN TrangThai NVARCHAR(50);
ALTER TABLE DonHang
ADD CONSTRAINT df_TrangThai DEFAULT(N'Chờ') FOR TrangThai;

ALTER TABLE DonHang
ALTER COLUMN GhiChu NVARCHAR(225) not null ;


CREATE TABLE ThongTinDonHang(
	IDDonHang INT,
	IDMedia INT,
	SoLuong INT,
	Gia INT,
	FOREIGN KEY (IDDonHang) REFERENCES DonHang(IDDonHang),
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia)
)

CREATE TABLE LichSuThanhToan(
	ID INT IDENTITY PRIMARY KEY,
	IDDonHang INT,
	NoiDung VARCHAR(225),
	FOREIGN KEY (IDDonHang) REFERENCES DonHang(IDDonHang)
)

CREATE TABLE Sale(
	IDSale INT IDENTITY PRIMARY KEY,
	StartTime DATE,
	EndTime DATE,
	Title VARCHAR(225),
	Sale INT
)

CREATE TABLE MediaSale (
	IDSale INT,
	IDMedia INT,
	FOREIGN KEY (IDSale) REFERENCES Sale(IDSale),
	FOREIGN KEY (IDMedia) REFERENCES Media(IDMedia)
)

INSERT INTO Users(Email, Pass, isAdmin) VALUES('admin@gmail.com','123456',1)

ALTER TABLE Media ADD image VARCHAR(225)

-- update vao ngay 22/12/2020
ALTER TABLE Media ADD ngay_nhap DATE

-- update vao ngay 23/12/2020;
ALTER TABLE Media
ALTER COLUMN ngay_nhap VARCHAR(50)


